<?php
require_once __DIR__ . '/../includes/app/admin_layout.php';
require_once __DIR__ . '/../includes/app/images.php';
hub_require_super_admin();
global $pdo, $DB_OK;
function hs_columns($table) { global $pdo; $out=[]; foreach ($pdo->query('SHOW COLUMNS FROM `'.str_replace('`','',$table).'`') as $r) $out[strtolower($r['Field'])]=$r['Field']; return $out; }
function hs_find($cols,$names) { foreach($names as $n) if(isset($cols[strtolower($n)])) return $cols[strtolower($n)]; return null; }
function hs_label($name) { return ucwords(str_replace('_',' ',preg_replace('/(?<!^)[A-Z]/',' $0',$name))); }
$error=null; $messages=hub_flash_messages(); $table=cms_preferences_table(); $rows=[]; $cats=[];
if (!$DB_OK || !($pdo instanceof PDO) || !$table) $error='Preference settings are not available.';
if (!$error) try {
  $cols=hs_columns($table); $id=hs_find($cols,['id']); $name=hs_find($cols,['name']); $value=hs_find($cols,['value']); $cat=hs_find($cols,['prefcat','pref_cat','category_id']); $sort=hs_find($cols,['sort']); $allow=hs_find($cols,['allowedit','allow_edit']); $arch=hs_find($cols,['archived']); $show=hs_find($cols,['showonweb','show_on_web']);
  if(!$id||!$value) throw new RuntimeException('The preferences table needs id and value columns.');
  $where=[]; if($arch)$where[]="`$arch`=0";
  $rows=$pdo->query('SELECT * FROM `'.$table.'`'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY '.($sort?"`$sort` ASC,":'')."`$id` ASC")->fetchAll(PDO::FETCH_ASSOC)?:[];
  if(hub_table_exists('cms_prefCat')) { $cc=hs_columns('cms_prefCat'); $cid=hs_find($cc,['id']); $cs=hs_find($cc,['sort']); if($cid) foreach($pdo->query('SELECT * FROM `cms_prefCat` ORDER BY '.($cs?"`$cs` ASC,":'')."`$cid` ASC")->fetchAll(PDO::FETCH_ASSOC)?:[] as $r) $cats[(string)$r[$cid]]=$r; }
} catch(Throwable $e) { $error=$e->getMessage(); }
$by=[]; foreach($rows as $r)$by[(string)$r[$id]]=$r; $active=(string)($_GET['category']??''); if($active===''&&$rows)$active=$cat?(string)($rows[0][$cat]??''):''; $edit=(string)($_GET['edit']??''); $row=$by[$edit]??null;
if(($_POST['action']??'')==='dev_setting_action') {
  if(!hub_is_developer()) $error='Developer access is required for temporary ordering controls.';
  elseif(!hub_verify_csrf($_POST['csrf']??'')) $error='Session expired. Please try again.';
  else try {
    $target=$by[(string)($_POST['preference_id']??'')]??null;
    if(!$target) throw new RuntimeException('Setting not found.');
    if(($_POST['dev_action']??'')==='toggle_web' && $show) {
      $next=strtolower((string)($target[$show]??''))==='yes'?'No':'Yes';
      $pdo->prepare('UPDATE `'.$table.'` SET `'.$show.'`=:value WHERE `'.$id.'`=:id LIMIT 1')->execute([':value'=>$next,':id'=>$target[$id]]);
    } elseif(($_POST['dev_action']??'')==='set_category' && $cat) {
      $newCategory=(string)($_POST['category_id']??'');
      if(!array_key_exists($newCategory,$cats)) throw new RuntimeException('Unknown category.');
      $pdo->prepare('UPDATE `'.$table.'` SET `'.$cat.'`=:value WHERE `'.$id.'`=:id LIMIT 1')->execute([':value'=>$newCategory,':id'=>$target[$id]]);
    }
    hub_flash('success','Temporary developer setting control applied.'); hub_redirect('/admin/settings.php?category='.rawurlencode($active));
  } catch(Throwable $e) { $error=$e->getMessage(); }
}
if($row&&$_SERVER['REQUEST_METHOD']==='POST') { if(!hub_verify_csrf($_POST['csrf']??''))$error='Session expired. Please try again.'; else try { $skip=['id','created','modified','migrule','logmask','showoncms','show_on_cms','allowedit','allow_edit']; $set=[];$params=[':id'=>$edit]; foreach($cols as $low=>$actual) if(!in_array($low,$skip,true)&&array_key_exists($actual,$_POST['setting']??[])){ $key=':v'.count($set);$set[]="`$actual`=$key";$params[$key]=trim((string)$_POST['setting'][$actual]); } if(($_FILES['value_image']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){$e=null;$file=hub_image_upload($_FILES['value_image'],'site_preference_image',(string)($row[$name]??'site-image'),$e);if(!$file)throw new RuntimeException($e?:'Image upload failed.');$set[]="`$value`=:image";$params[':image']=$file;} if($set)$pdo->prepare('UPDATE `'.$table.'` SET '.implode(',',$set)." WHERE `$id`=:id LIMIT 1")->execute($params); hub_flash('success','Setting updated.');hub_redirect('/admin/settings.php?category='.rawurlencode($active)); }catch(Throwable $e){$error=$e->getMessage();} }
function hs_catname($key,$cats){foreach(['name','title','label','prefcat'] as $n)if(!empty($cats[$key][$n]))return$cats[$key][$n];return$key===''?'General':'Category '.$key;}
$tabs=[]; foreach($cats as $key=>$categoryRow) $tabs[(string)$key]=hs_catname((string)$key,$cats); if(!$tabs) foreach($rows as $r){$key=$cat?(string)($r[$cat]??''):'';$tabs[$key]=hs_catname($key,$cats);}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Settings</title><link rel="stylesheet" href="/css/hub.css"><style>.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:15px 0}.tabs a{padding:8px 12px;border:1px solid #ccc;border-radius:5px;text-decoration:none}.tabs .active{background:#26333b;color:white}.settings-table{table-layout:fixed;width:100%}.settings-table th button{border:0;background:none;font:inherit;font-weight:bold;cursor:pointer}.settings-table td:nth-child(2){max-width:128ch;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.settings-table .but2{background:#f1f5f6;border-color:#cbd7da;color:#34464d;margin:2px}.settings-table .web-on{background:#e7f5ea;border-color:#abd9b4;color:#26743a}.settings-table .web-off{background:#fbe9e9;border-color:#e4b8b8;color:#a93636}</style></head><body class="admin-page"><?php echo hub_admin_header('super');?><div class="stack"><div class="wrap"><div class="card"><p class="brand">Tools</p><h1>Site settings</h1><?php if($error)echo '<div class="alert error">'.hub_h($error).'</div>';foreach($messages as $m)echo '<div class="alert '.hub_h($m['type']).'">'.hub_h($m['message']).'</div>';?></div>
<?php if($row): ?><div class="card"><h2>Edit <?php echo hub_h((string)($row[$name]??'Setting'));?></h2><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?php echo hub_h(hub_csrf_token());?>"><div class="form-grid"><?php $skip=['id','created','modified','migrule','logmask','showoncms','show_on_cms','allowedit','allow_edit'];foreach($cols as $low=>$actual){if(in_array($low,$skip,true))continue;$v=(string)($row[$actual]??'');echo '<div><label>'.hub_h(hs_label($actual)).'</label><input name="setting['.hub_h($actual).']" value="'.hub_h($v).'"></div>';}?><div><label>Replace image</label><input type="file" name="value_image" accept="image/*"></div></div><button class="but1">Save setting</button> <a href="/admin/settings.php?category=<?php echo rawurlencode($active);?>">Cancel</a></form></div>
<?php else: ?><div class="card"><nav class="tabs"><?php foreach($tabs as $key=>$label)echo '<a class="'.($active===$key?'active':'').'" href="/admin/settings.php?category='.rawurlencode($key).'">'.hub_h($label).'</a>';?></nav><input id="q" type="search" placeholder="Search this category"><table class="table settings-table" id="t"><thead><tr><th><button data-n="0">Label</button></th><th><button data-n="1">Value</button></th><th><button data-n="2">Sort</button></th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r){if(($cat?(string)($r[$cat]??''):'')!==$active)continue;echo '<tr><td>'.hub_h((string)($r[$name]??$r[$id])).'</td><td>'.hub_h((string)$r[$value]).'</td><td>'.hub_h((string)($sort?($r[$sort]??''):'')).'</td><td><a class="but2" href="/admin/settings.php?category='.rawurlencode($active).'&edit='.(int)$r[$id].'">Edit</a>';if(hub_is_developer()){echo '<form method="post" style="display:inline"><input type="hidden" name="csrf" value="'.hub_h(hub_csrf_token()).'"><input type="hidden" name="action" value="dev_setting_action"><input type="hidden" name="preference_id" value="'.(int)$r[$id].'"><input type="hidden" name="dev_action" value="toggle_web"><button class="but2 '.(strtolower((string)($r[$show]??''))==='yes'?'web-on':'web-off').'">Show On Web</button></form>';foreach($tabs as $ck=>$cl)echo '<form method="post" style="display:inline"><input type="hidden" name="csrf" value="'.hub_h(hub_csrf_token()).'"><input type="hidden" name="action" value="dev_setting_action"><input type="hidden" name="preference_id" value="'.(int)$r[$id].'"><input type="hidden" name="dev_action" value="set_category"><input type="hidden" name="category_id" value="'.hub_h($ck).'"><button class="but2">'.hub_h($cl).'</button></form>';}echo '</td></tr>';}?></tbody></table></div><script>let b=document.querySelector('#t tbody');q.oninput=()=>[...b.rows].forEach(r=>r.hidden=!r.innerText.toLowerCase().includes(q.value.toLowerCase()));document.querySelectorAll('[data-n]').forEach(x=>x.onclick=()=>{let n=+x.dataset.n,a=[...b.rows];a.sort((r,s)=>n==2?(+r.cells[n].innerText)-(+s.cells[n].innerText):r.cells[n].innerText.localeCompare(s.cells[n].innerText));a.forEach(r=>b.append(r))})</script><?php endif;?></div></div></body></html>
